import { withMermaid } from "vitepress-plugin-mermaid";

export default withMermaid({
  mermaid: {
    theme: "dark",
    themeVariables: {
      background: "transparent",
      fontFamily: "inherit",
    },
  },
  title: "Clef",
  description: "Keep encrypted secrets alongside your code. One commit hash = your entire system.",

  appearance: "dark",

  head: [["link", { rel: "icon", href: "/logo.svg" }]],

  themeConfig: {
    logo: "/logo.svg",

    search: {
      provider: "local",
    },

    socialLinks: [
      { icon: "github", link: "https://github.com/clef-sh/clef" },
      {
        icon: {
          svg: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>',
        },
        link: "https://clef.sh",
      },
    ],

    editLink: {
      pattern: "https://github.com/clef-sh/clef/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },

    footer: {
      message: "MIT License | Made by the Clef contributors",
    },

    nav: [
      { text: "Guide", link: "/guide/introduction" },
      { text: "CLI Reference", link: "/cli/overview" },
      { text: "UI", link: "/ui/overview" },
      { text: "Backends", link: "/backends/age" },
      { text: "Schemas", link: "/schemas/overview" },
      { text: "API", link: "/api/" },
      { text: "Contributing", link: "/contributing/development-setup" },
    ],

    sidebar: {
      "/guide/": [
        {
          text: "Guide",
          items: [
            { text: "Introduction", link: "/guide/introduction" },
            { text: "Installation", link: "/guide/installation" },
            { text: "Quick Start", link: "/guide/quick-start" },
            { text: "Migrating to Clef", link: "/guide/migrating" },
            { text: "Core Concepts", link: "/guide/concepts" },
            { text: "Key Storage", link: "/guide/key-storage" },
            { text: "Pending Values", link: "/guide/pending-values" },
            { text: "CI/CD Integration", link: "/guide/ci-cd" },
            { text: "Team Setup", link: "/guide/team-setup" },
            { text: "Merge Conflicts", link: "/guide/merge-conflicts" },
            { text: "Scanning for Secrets", link: "/guide/scanning" },
            { text: "Service Identities", link: "/guide/service-identities" },
            { text: "Manifest Reference", link: "/guide/manifest" },
          ],
        },
      ],
      "/cli/": [
        {
          text: "CLI Reference",
          items: [
            { text: "Overview", link: "/cli/overview" },
            { text: "clef doctor", link: "/cli/doctor" },
            { text: "clef init", link: "/cli/init" },
            { text: "clef update", link: "/cli/update" },
            { text: "clef get", link: "/cli/get" },
            { text: "clef set", link: "/cli/set" },
            { text: "clef compare", link: "/cli/compare" },
            { text: "clef delete", link: "/cli/delete" },
            { text: "clef diff", link: "/cli/diff" },
            { text: "clef lint", link: "/cli/lint" },
            { text: "clef scan", link: "/cli/scan" },
            { text: "clef rotate", link: "/cli/rotate" },
            { text: "clef recipients", link: "/cli/recipients" },
            { text: "clef hooks", link: "/cli/hooks" },
            { text: "clef exec", link: "/cli/exec" },
            { text: "clef export", link: "/cli/export" },
            { text: "clef import", link: "/cli/import" },
            { text: "clef service", link: "/cli/service" },
            { text: "clef pack", link: "/cli/pack" },
            { text: "clef agent", link: "/cli/agent" },
            { text: "clef ui", link: "/cli/ui" },
          ],
        },
      ],
      "/ui/": [
        {
          text: "Web UI",
          items: [
            { text: "Overview", link: "/ui/overview" },
            { text: "Matrix View", link: "/ui/matrix-view" },
            { text: "Namespace Editor", link: "/ui/editor" },
            { text: "Diff View", link: "/ui/diff-view" },
            { text: "Lint View", link: "/ui/lint-view" },
          ],
        },
      ],
      "/backends/": [
        {
          text: "Encryption Backends",
          items: [
            { text: "age (recommended)", link: "/backends/age" },
            { text: "AWS KMS", link: "/backends/aws-kms" },
            { text: "GCP KMS", link: "/backends/gcp-kms" },
            { text: "PGP", link: "/backends/pgp" },
          ],
        },
      ],
      "/schemas/": [
        {
          text: "Schemas",
          items: [
            { text: "Overview", link: "/schemas/overview" },
            { text: "Schema Reference", link: "/schemas/reference" },
          ],
        },
      ],
      "/contributing/": [
        {
          text: "Contributing",
          items: [
            { text: "Development Setup", link: "/contributing/development-setup" },
            { text: "Architecture", link: "/contributing/architecture" },
            { text: "Testing", link: "/contributing/testing" },
            { text: "Releasing", link: "/contributing/releasing" },
          ],
        },
      ],
      "/api/": [
        {
          text: "@clef-sh/core",
          items: [{ text: "Overview", link: "/api/" }],
        },
        {
          text: "Classes",
          collapsed: false,
          items: [
            { text: "ManifestParser", link: "/api/classes/ManifestParser" },
            { text: "MatrixManager", link: "/api/classes/MatrixManager" },
            { text: "SopsClient", link: "/api/classes/SopsClient" },
            { text: "LintRunner", link: "/api/classes/LintRunner" },
            { text: "DiffEngine", link: "/api/classes/DiffEngine" },
            { text: "BulkOps", link: "/api/classes/BulkOps" },
            { text: "ScanRunner", link: "/api/classes/ScanRunner" },
            { text: "SchemaValidator", link: "/api/classes/SchemaValidator" },
            { text: "GitIntegration", link: "/api/classes/GitIntegration" },
            { text: "ConsumptionClient", link: "/api/classes/ConsumptionClient" },
            { text: "ImportRunner", link: "/api/classes/ImportRunner" },
            { text: "RecipientManager", link: "/api/classes/RecipientManager" },
            { text: "ServiceIdentityManager", link: "/api/classes/ServiceIdentityManager" },
            { text: "SopsMergeDriver", link: "/api/classes/SopsMergeDriver" },
          ],
        },
        {
          text: "Error Classes",
          collapsed: true,
          items: [
            { text: "ClefError", link: "/api/classes/ClefError" },
            { text: "ManifestValidationError", link: "/api/classes/ManifestValidationError" },
            { text: "SopsDecryptionError", link: "/api/classes/SopsDecryptionError" },
            { text: "SopsEncryptionError", link: "/api/classes/SopsEncryptionError" },
            { text: "SopsKeyNotFoundError", link: "/api/classes/SopsKeyNotFoundError" },
            { text: "SopsMissingError", link: "/api/classes/SopsMissingError" },
            { text: "SopsVersionError", link: "/api/classes/SopsVersionError" },
            { text: "GitOperationError", link: "/api/classes/GitOperationError" },
            { text: "SchemaLoadError", link: "/api/classes/SchemaLoadError" },
          ],
        },
        {
          text: "Functions",
          collapsed: true,
          items: [
            { text: "assertSops", link: "/api/functions/assertSops" },
            { text: "checkAll", link: "/api/functions/checkAll" },
            { text: "checkDependency", link: "/api/functions/checkDependency" },
            { text: "deriveAgePublicKey", link: "/api/functions/deriveAgePublicKey" },
            { text: "detectFormat", link: "/api/functions/detectFormat" },
            { text: "formatAgeKeyFile", link: "/api/functions/formatAgeKeyFile" },
            { text: "generateAgeIdentity", link: "/api/functions/generateAgeIdentity" },
            { text: "generateRandomValue", link: "/api/functions/generateRandomValue" },
            { text: "getPendingKeys", link: "/api/functions/getPendingKeys" },
            { text: "isHighEntropy", link: "/api/functions/isHighEntropy" },
            { text: "isPending", link: "/api/functions/isPending" },
            { text: "keyPreview", link: "/api/functions/keyPreview" },
            { text: "loadIgnoreRules", link: "/api/functions/loadIgnoreRules" },
            { text: "loadMetadata", link: "/api/functions/loadMetadata" },
            { text: "markPending", link: "/api/functions/markPending" },
            { text: "markPendingWithRetry", link: "/api/functions/markPendingWithRetry" },
            { text: "markResolved", link: "/api/functions/markResolved" },
            { text: "matchPatterns", link: "/api/functions/matchPatterns" },
            { text: "metadataPath", link: "/api/functions/metadataPath" },
            { text: "parse", link: "/api/functions/parse" },
            { text: "parseDotenv", link: "/api/functions/parseDotenv" },
            { text: "parseIgnoreContent", link: "/api/functions/parseIgnoreContent" },
            { text: "parseJson", link: "/api/functions/parseJson" },
            { text: "parseYaml", link: "/api/functions/parseYaml" },
            { text: "redactValue", link: "/api/functions/redactValue" },
            { text: "resetSopsResolution", link: "/api/functions/resetSopsResolution" },
            { text: "resolveBackendConfig", link: "/api/functions/resolveBackendConfig" },
            {
              text: "resolveRecipientsForEnvironment",
              link: "/api/functions/resolveRecipientsForEnvironment",
            },
            { text: "resolveSopsPath", link: "/api/functions/resolveSopsPath" },
            { text: "saveMetadata", link: "/api/functions/saveMetadata" },
            { text: "shannonEntropy", link: "/api/functions/shannonEntropy" },
            { text: "shouldIgnoreFile", link: "/api/functions/shouldIgnoreFile" },
            { text: "shouldIgnoreMatch", link: "/api/functions/shouldIgnoreMatch" },
            { text: "validateAgePublicKey", link: "/api/functions/validateAgePublicKey" },
          ],
        },
        {
          text: "Interfaces",
          collapsed: true,
          items: [
            { text: "AgeIdentity", link: "/api/interfaces/AgeIdentity" },
            { text: "AgeKeyValidation", link: "/api/interfaces/AgeKeyValidation" },
            { text: "ClefEnvironment", link: "/api/interfaces/ClefEnvironment" },
            { text: "ClefIgnoreRules", link: "/api/interfaces/ClefIgnoreRules" },
            { text: "ClefLocalConfig", link: "/api/interfaces/ClefLocalConfig" },
            { text: "ClefManifest", link: "/api/interfaces/ClefManifest" },
            { text: "ClefNamespace", link: "/api/interfaces/ClefNamespace" },
            { text: "DecryptedFile", link: "/api/interfaces/DecryptedFile" },
            { text: "DependencyStatus", link: "/api/interfaces/DependencyStatus" },
            { text: "DependencyVersion", link: "/api/interfaces/DependencyVersion" },
            { text: "DiffResult", link: "/api/interfaces/DiffResult" },
            { text: "DiffRow", link: "/api/interfaces/DiffRow" },
            { text: "ExecOptions", link: "/api/interfaces/ExecOptions" },
            { text: "EncryptionBackend", link: "/api/interfaces/EncryptionBackend" },
            { text: "EnvironmentSopsOverride", link: "/api/interfaces/EnvironmentSopsOverride" },
            { text: "ExportOptions", link: "/api/interfaces/ExportOptions" },
            { text: "GitCommit", link: "/api/interfaces/GitCommit" },
            { text: "GitStatus", link: "/api/interfaces/GitStatus" },
            { text: "ImportOptions", link: "/api/interfaces/ImportOptions" },
            { text: "ImportResult", link: "/api/interfaces/ImportResult" },
            { text: "LintIssue", link: "/api/interfaces/LintIssue" },
            { text: "LintResult", link: "/api/interfaces/LintResult" },
            { text: "MatrixCell", link: "/api/interfaces/MatrixCell" },
            { text: "MatrixIssue", link: "/api/interfaces/MatrixIssue" },
            { text: "MatrixStatus", link: "/api/interfaces/MatrixStatus" },
            { text: "MergeKey", link: "/api/interfaces/MergeKey" },
            { text: "MergeResult", link: "/api/interfaces/MergeResult" },
            { text: "NamespaceSchema", link: "/api/interfaces/NamespaceSchema" },
            { text: "ParsedImport", link: "/api/interfaces/ParsedImport" },
            { text: "PendingKey", link: "/api/interfaces/PendingKey" },
            { text: "PendingMetadata", link: "/api/interfaces/PendingMetadata" },
            { text: "Recipient", link: "/api/interfaces/Recipient" },
            { text: "RecipientsResult", link: "/api/interfaces/RecipientsResult" },
            { text: "ScanMatch", link: "/api/interfaces/ScanMatch" },
            { text: "ScanOptions", link: "/api/interfaces/ScanOptions" },
            { text: "ScanResult", link: "/api/interfaces/ScanResult" },
            {
              text: "ServiceIdentityDefinition",
              link: "/api/interfaces/ServiceIdentityDefinition",
            },
            {
              text: "ServiceIdentityDriftIssue",
              link: "/api/interfaces/ServiceIdentityDriftIssue",
            },
            {
              text: "ServiceIdentityEnvironmentConfig",
              link: "/api/interfaces/ServiceIdentityEnvironmentConfig",
            },
            { text: "SchemaKey", link: "/api/interfaces/SchemaKey" },
            { text: "SopsConfig", link: "/api/interfaces/SopsConfig" },
            { text: "SopsMetadata", link: "/api/interfaces/SopsMetadata" },
            { text: "SubprocessOptions", link: "/api/interfaces/SubprocessOptions" },
            { text: "SubprocessResult", link: "/api/interfaces/SubprocessResult" },
            { text: "SubprocessRunner", link: "/api/interfaces/SubprocessRunner" },
            { text: "ValidationError", link: "/api/interfaces/ValidationError" },
            { text: "ValidationResult", link: "/api/interfaces/ValidationResult" },
            { text: "ValidationWarning", link: "/api/interfaces/ValidationWarning" },
          ],
        },
        {
          text: "Type Aliases",
          collapsed: true,
          items: [
            { text: "DiffStatus", link: "/api/type-aliases/DiffStatus" },
            { text: "ImportFormat", link: "/api/type-aliases/ImportFormat" },
            { text: "LintCategory", link: "/api/type-aliases/LintCategory" },
            { text: "LintSeverity", link: "/api/type-aliases/LintSeverity" },
            { text: "MergeKeyStatus", link: "/api/type-aliases/MergeKeyStatus" },
            { text: "SopsResolution", link: "/api/type-aliases/SopsResolution" },
            { text: "SopsSource", link: "/api/type-aliases/SopsSource" },
          ],
        },
        {
          text: "Constants",
          collapsed: true,
          items: [
            {
              text: "CLEF_MANIFEST_FILENAME",
              link: "/api/variables/CLEF_MANIFEST_FILENAME",
            },
            {
              text: "CLEF_SUPPORTED_EXTENSIONS",
              link: "/api/variables/CLEF_SUPPORTED_EXTENSIONS",
            },
            { text: "REQUIREMENTS", link: "/api/variables/REQUIREMENTS" },
          ],
        },
      ],
    },
  },
});
