// Build-time mermaid → SVG plugin.
//
// Why: vitepress-plugin-mermaid renders client-side, which (a) ships ~100 KB
// of mermaid + dompurify + uuid to every visitor (security alerts come along
// for the ride), (b) declares vp1 as a peer and so blocks vp2 from hoisting
// in our workspace tree (forcing the registry build symlink hack). Rendering
// to static SVGs at build time eliminates both.
//
// What this does:
//   - Hooks markdown-it's fence handler for ```mermaid blocks
//   - Computes a SHA-256 of the block content; cache key splits dark/light
//   - Renders <hash>.dark.svg + <hash>.light.svg via mmdc on first miss
//   - Emits paired <img src="data:image/svg+xml;base64,..."> tags; CSS in
//     theme/style.css hides the wrong one based on vitepress's `html.dark`
//     class
//
// Why data-URI <img> (not <img src="/diagrams/...">, not inline <svg>):
//   - <img src> to a /diagrams/ path: Vue's template compiler auto-rewrites
//     it into a vite asset import (?import suffix). Files in docs/public/
//     are not in vite's module graph, so those imports fall through to vp's
//     SPA-shell HTML and the browser shows broken images.
//   - inline <svg>: mmdc emits `<style>` blocks inside the SVG for theme
//     colours; Vue's template compiler refuses to process <style> tags
//     embedded in component templates ("Tags with side effect ... are
//     ignored in client component templates"). Hard error in dev.
//   - data-URI <img>: opaque string to Vue, no asset rewrite, no template
//     parsing. Costs ~33% HTML weight per diagram (base64 overhead) but
//     diagrams are small (~20 KB raw) and only loaded on pages with them.
//
// SVGs land in docs/public/diagrams/ as a content-hash cache; the .gitignored
// directory is regenerated by mmdc on miss. The committed/runtime URL is the
// data-URI in the page HTML — nothing fetches the public/ files at runtime.

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type MarkdownIt from "markdown-it";

// vitepress passes a MarkdownItAsync, but we only touch renderer.rules.fence
// which is shared with the sync MarkdownIt type — accept either by widening
// to the renderer-only surface we need.
type MarkdownItLike = Pick<MarkdownIt, "renderer">;
type FenceRule = NonNullable<MarkdownItLike["renderer"]["rules"]["fence"]>;

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DOCS_ROOT = path.resolve(__dirname, "..", "..");
const DIAGRAMS_DIR = path.join(DOCS_ROOT, "public", "diagrams");

// Resolve mmdc from whichever node_modules npm hoisted it into. Walks up
// from docs/ so it picks up either docs/node_modules/.bin/mmdc (per-workspace)
// or node_modules/.bin/mmdc (hoisted to root).
function resolveMmdcBin(): string {
  let dir = DOCS_ROOT;
  while (true) {
    const candidate = path.join(dir, "node_modules", ".bin", "mmdc");
    if (existsSync(candidate)) return candidate;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  throw new Error(
    "mermaid-svg plugin: could not find `mmdc` binary. Is `@mermaid-js/mermaid-cli` installed?",
  );
}

let mmdcBinCache: string | null = null;
function mmdcBin(): string {
  if (!mmdcBinCache) mmdcBinCache = resolveMmdcBin();
  return mmdcBinCache;
}


// Diagram font — Arial. Pinned because:
//   1. It's bundled with puppeteer's chromium so mmdc can measure glyph widths
//      directly (no @font-face dance required).
//   2. It's available on every browser on every platform, so the live page
//      renders the diagram in the same font mmdc measured against. Identical
//      metrics on both ends → no text clipping.
// We previously tried Instrument Sans (the body font) so diagrams would
// blend; mermaid's text measurement didn't honor the @font-face data-URI
// reliably and boxes ended up sized for the chromium fallback (Verdana-ish),
// then the live page rendered Instrument Sans (wider) and labels overflowed.
const DIAGRAM_FONT = "Arial, sans-serif";

type Theme = "dark" | "light";

const THEME_CONFIG: Record<Theme, { theme: string; backgroundColor: string }> = {
  dark: { theme: "dark", backgroundColor: "transparent" },
  light: { theme: "default", backgroundColor: "transparent" },
};

function ensureDiagramsDir(): void {
  if (!existsSync(DIAGRAMS_DIR)) {
    mkdirSync(DIAGRAMS_DIR, { recursive: true });
  }
}

function svgPathFor(hash: string, theme: Theme): string {
  return path.join(DIAGRAMS_DIR, `${hash}.${theme}.svg`);
}

function renderOne(source: string, hash: string, theme: Theme): void {
  const outPath = svgPathFor(hash, theme);
  if (existsSync(outPath)) return;

  ensureDiagramsDir();

  const cfg = THEME_CONFIG[theme];
  const tmp = mkdtempSync(path.join(tmpdir(), "mermaid-svg-"));
  const inputPath = path.join(tmp, "input.mmd");
  const configPath = path.join(tmp, "config.json");

  try {
    writeFileSync(inputPath, source, "utf8");
    writeFileSync(
      configPath,
      JSON.stringify({
        theme: cfg.theme,
        themeVariables: { fontFamily: DIAGRAM_FONT },
        flowchart: { padding: 12 },
      }),
      "utf8",
    );

    execFileSync(
      mmdcBin(),
      [
        "-i",
        inputPath,
        "-o",
        outPath,
        "-b",
        cfg.backgroundColor,
        "-c",
        configPath,
        "--quiet",
      ],
      { stdio: ["ignore", "ignore", "inherit"] },
    );
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

function renderBoth(source: string): { hash: string } {
  // Hash the source only — themes are independent variants of the same content,
  // so a change to one block invalidates both SVGs together.
  const hash = createHash("sha256").update(source).digest("hex").slice(0, 16);
  renderOne(source, hash, "dark");
  renderOne(source, hash, "light");
  return { hash };
}

function loadSvg(filePath: string): string {
  return readFileSync(filePath, "utf8");
}

function htmlAttrEscape(s: string): string {
  // Used inside a double-quoted HTML attribute value; escape the chars that
  // would prematurely close the attribute or break the parser. The string is
  // already JSON-escaped (so `\` and `"` are doubled there), but we still
  // need to flip raw `"` from JSON's outer quotes, `&`, and `<` for HTML.
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

export function mermaidSvgPlugin(md: MarkdownItLike): void {
  const fence = md.renderer.rules.fence;
  if (!fence) {
    throw new Error("markdown-it: no default fence renderer to wrap");
  }

  const wrapped: FenceRule = (tokens, idx, options, env, self) => {
    const token = tokens[idx];
    if (token.info.trim() !== "mermaid") {
      return fence(tokens, idx, options, env, self);
    }

    const { hash } = renderBoth(token.content);
    const darkSvg = loadSvg(svgPathFor(hash, "dark"));
    const lightSvg = loadSvg(svgPathFor(hash, "light"));

    // Inline via v-html so the SVG ends up in the page DOM (and inherits the
    // page font from its `font-family: inherit` <style>) WITHOUT going through
    // Vue's template compiler. Vue rejects bare <style> tags inside templates
    // ("Tags with side effect ... are ignored"), but v-html is evaluated at
    // runtime and sets innerHTML directly — the browser parses the SVG as a
    // DOM tree, no template compile involved.
    //
    // The expression value must be a valid JS string literal; JSON.stringify
    // escapes quotes, backslashes and newlines safely. We then HTML-escape
    // the result so it survives as the value of an HTML attribute.
    const darkExpr = htmlAttrEscape(JSON.stringify(darkSvg));
    const lightExpr = htmlAttrEscape(JSON.stringify(lightSvg));

    return (
      `<div class="mermaid-diagram">` +
      `<div class="mermaid-diagram-light" v-html="${lightExpr}"></div>` +
      `<div class="mermaid-diagram-dark" v-html="${darkExpr}"></div>` +
      `</div>`
    );
  };

  md.renderer.rules.fence = wrapped;
}
