import * as fs from "fs";
import { BundleGenerator } from "./generator";
import { ClefManifest, EncryptionBackend, BundleConfig, DecryptedFile } from "../types";
import { MatrixManager } from "../matrix/manager";

jest.mock("fs");

// Mock age-encryption
jest.mock(
  "age-encryption",
  () => ({
    Encrypter: jest.fn().mockImplementation(() => ({
      addRecipient: jest.fn(),
      encrypt: jest
        .fn()
        .mockResolvedValue(
          "-----BEGIN AGE ENCRYPTED FILE-----\nencrypted\n-----END AGE ENCRYPTED FILE-----",
        ),
    })),
  }),
  { virtual: true },
);

const mockFs = fs as jest.Mocked<typeof fs>;

function baseManifest(): ClefManifest {
  return {
    version: 1,
    environments: [
      { name: "dev", description: "Development" },
      { name: "staging", description: "Staging" },
    ],
    namespaces: [
      { name: "api", description: "API secrets" },
      { name: "database", description: "DB config" },
    ],
    sops: { default_backend: "age" },
    file_pattern: "{namespace}/{environment}.enc.yaml",
    service_identities: [
      {
        name: "api-gateway",
        description: "API gateway service",
        namespaces: ["api"],
        environments: {
          dev: { recipient: "age1devkey" },
          staging: { recipient: "age1stgkey" },
        },
      },
      {
        name: "multi-svc",
        description: "Multi-namespace service",
        namespaces: ["api", "database"],
        environments: {
          dev: { recipient: "age1multidev" },
          staging: { recipient: "age1multistg" },
        },
      },
    ],
  };
}

function mockEncryption(): jest.Mocked<EncryptionBackend> {
  return {
    decrypt: jest.fn(),
    encrypt: jest.fn(),
    reEncrypt: jest.fn(),
    addRecipient: jest.fn(),
    removeRecipient: jest.fn(),
    validateEncryption: jest.fn(),
    getMetadata: jest.fn(),
  };
}

describe("BundleGenerator", () => {
  let encryption: jest.Mocked<EncryptionBackend>;
  let matrixManager: MatrixManager;
  let generator: BundleGenerator;

  beforeEach(() => {
    jest.clearAllMocks();
    encryption = mockEncryption();
    matrixManager = new MatrixManager();
    generator = new BundleGenerator(encryption, matrixManager);

    mockFs.existsSync.mockImplementation((p) => {
      const s = String(p);
      return s.includes(".enc.yaml");
    });
    mockFs.writeFileSync.mockImplementation(() => {});
    mockFs.mkdirSync.mockImplementation(() => undefined as unknown as string);
  });

  it("should generate a bundle for a single-namespace identity", async () => {
    const decrypted: DecryptedFile = {
      values: { DATABASE_URL: "postgres://...", API_KEY: "secret123" },
      metadata: { backend: "age", recipients: ["age1devkey"], lastModified: new Date() },
    };
    encryption.decrypt.mockResolvedValue(decrypted);

    const config: BundleConfig = {
      identity: "api-gateway",
      environment: "dev",
      outputPath: "/output/secrets.mjs",
      format: "esm",
    };

    const result = await generator.generate(config, baseManifest(), "/repo");

    expect(result.outputPath).toBe("/output/secrets.mjs");
    expect(result.namespaceCount).toBe(1);
    expect(result.keyCount).toBe(2);
    expect(result.bundleSize).toBeGreaterThan(0);
    expect(mockFs.writeFileSync).toHaveBeenCalledWith(
      "/output/secrets.mjs",
      expect.stringContaining("Generated by clef bundle"),
      "utf-8",
    );
  });

  it("should use namespace-prefixed keys for multi-namespace identity", async () => {
    const apiDecrypted: DecryptedFile = {
      values: { API_KEY: "key1" },
      metadata: { backend: "age", recipients: ["age1multidev"], lastModified: new Date() },
    };
    const dbDecrypted: DecryptedFile = {
      values: { DB_HOST: "localhost" },
      metadata: { backend: "age", recipients: ["age1multidev"], lastModified: new Date() },
    };
    encryption.decrypt.mockResolvedValueOnce(apiDecrypted).mockResolvedValueOnce(dbDecrypted);

    const config: BundleConfig = {
      identity: "multi-svc",
      environment: "dev",
      outputPath: "/output/secrets.cjs",
      format: "cjs",
    };

    const result = await generator.generate(config, baseManifest(), "/repo");

    expect(result.keyCount).toBe(2);
    // The written source should contain namespace-prefixed keys
    const writtenSource = (mockFs.writeFileSync as jest.Mock).mock.calls[0][1] as string;
    expect(writtenSource).toContain("api/API_KEY");
    expect(writtenSource).toContain("database/DB_HOST");
  });

  it("should throw if identity not found", async () => {
    const config: BundleConfig = {
      identity: "nonexistent",
      environment: "dev",
      outputPath: "/output/secrets.mjs",
      format: "esm",
    };

    await expect(generator.generate(config, baseManifest(), "/repo")).rejects.toThrow("not found");
  });

  it("should throw if environment not found on identity", async () => {
    const config: BundleConfig = {
      identity: "api-gateway",
      environment: "production",
      outputPath: "/output/secrets.mjs",
      format: "esm",
    };

    await expect(generator.generate(config, baseManifest(), "/repo")).rejects.toThrow("not found");
  });

  it("should create output directory if it does not exist", async () => {
    const decrypted: DecryptedFile = {
      values: { KEY: "val" },
      metadata: { backend: "age", recipients: ["age1devkey"], lastModified: new Date() },
    };
    encryption.decrypt.mockResolvedValue(decrypted);
    mockFs.existsSync.mockImplementation((p) => {
      if (String(p) === "/new-dir") return false;
      return String(p).includes(".enc.yaml");
    });

    const config: BundleConfig = {
      identity: "api-gateway",
      environment: "dev",
      outputPath: "/new-dir/secrets.mjs",
      format: "esm",
    };

    await generator.generate(config, baseManifest(), "/repo");

    expect(mockFs.mkdirSync).toHaveBeenCalledWith("/new-dir", { recursive: true });
  });

  it("should handle zero keys gracefully", async () => {
    const decrypted: DecryptedFile = {
      values: {},
      metadata: { backend: "age", recipients: ["age1devkey"], lastModified: new Date() },
    };
    encryption.decrypt.mockResolvedValue(decrypted);

    const config: BundleConfig = {
      identity: "api-gateway",
      environment: "dev",
      outputPath: "/output/secrets.mjs",
      format: "esm",
    };

    const result = await generator.generate(config, baseManifest(), "/repo");
    expect(result.keyCount).toBe(0);
  });

  it("should generate CJS format", async () => {
    const decrypted: DecryptedFile = {
      values: { KEY: "val" },
      metadata: { backend: "age", recipients: ["age1devkey"], lastModified: new Date() },
    };
    encryption.decrypt.mockResolvedValue(decrypted);

    const config: BundleConfig = {
      identity: "api-gateway",
      environment: "dev",
      outputPath: "/output/secrets.cjs",
      format: "cjs",
    };

    await generator.generate(config, baseManifest(), "/repo");

    const writtenSource = (mockFs.writeFileSync as jest.Mock).mock.calls[0][1] as string;
    expect(writtenSource).toContain("module.exports");
  });
});
