/**
 * Generates the runtime module source code for a service identity bundle.
 *
 * The generated module uses `age-encryption` (pure JS) to decrypt an embedded
 * age-encrypted blob. No sops binary or git repo needed at runtime.
 */

/**
 * Generate the JS source code for a runtime secrets module.
 *
 * @param armoredCiphertext - PEM-armored age ciphertext containing the encrypted JSON blob.
 * @param keys - List of secret key names available in the bundle (for introspection).
 * @param format - Output module format: "esm" or "cjs".
 */
export function generateRuntimeModule(
  armoredCiphertext: string,
  keys: string[],
  format: "esm" | "cjs",
): string {
  const keysJson = JSON.stringify(keys);
  const escapedCiphertext = armoredCiphertext
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$");

  if (format === "esm") {
    return `// Generated by clef bundle — do not edit
const CIPHERTEXT = \`${escapedCiphertext}\`;

export const KEYS = Object.freeze(${keysJson});

let _cache = null;
let _pending = null;

async function _decrypt(keyProvider) {
  const { Decrypter } = await import("age-encryption");
  const d = new Decrypter();
  const privateKey = await keyProvider();
  d.addIdentity(privateKey);
  const plaintext = await d.decrypt(CIPHERTEXT, "text");
  return JSON.parse(plaintext);
}

async function _ensureDecrypted(keyProvider) {
  if (_cache) return _cache;
  if (_pending) return _pending;
  _pending = _decrypt(keyProvider).then((values) => {
    _cache = values;
    _pending = null;
    return values;
  }).catch((err) => {
    _pending = null;
    throw err;
  });
  return _pending;
}

export async function getSecret(key, keyProvider) {
  const values = await _ensureDecrypted(keyProvider);
  if (!(key in values)) {
    throw new Error(\`Secret key "\${key}" not found. Available: \${KEYS.join(", ")}\`);
  }
  return values[key];
}

export async function getAllSecrets(keyProvider) {
  return { ...(await _ensureDecrypted(keyProvider)) };
}

/**
 * Clear the decrypted secrets cache. Call this when secrets have been rotated
 * and you need to force a fresh decrypt on the next getSecret()/getAllSecrets() call.
 */
export function clearCache() {
  _cache = null;
  _pending = null;
}
`;
  }

  // CJS format
  return `// Generated by clef bundle — do not edit
"use strict";

const CIPHERTEXT = \`${escapedCiphertext}\`;

const KEYS = Object.freeze(${keysJson});

let _cache = null;
let _pending = null;

async function _decrypt(keyProvider) {
  const { Decrypter } = await import("age-encryption");
  const d = new Decrypter();
  const privateKey = await keyProvider();
  d.addIdentity(privateKey);
  const plaintext = await d.decrypt(CIPHERTEXT, "text");
  return JSON.parse(plaintext);
}

async function _ensureDecrypted(keyProvider) {
  if (_cache) return _cache;
  if (_pending) return _pending;
  _pending = _decrypt(keyProvider).then((values) => {
    _cache = values;
    _pending = null;
    return values;
  }).catch((err) => {
    _pending = null;
    throw err;
  });
  return _pending;
}

async function getSecret(key, keyProvider) {
  const values = await _ensureDecrypted(keyProvider);
  if (!(key in values)) {
    throw new Error(\`Secret key "\${key}" not found. Available: \${KEYS.join(", ")}\`);
  }
  return values[key];
}

async function getAllSecrets(keyProvider) {
  return { ...(await _ensureDecrypted(keyProvider)) };
}

/**
 * Clear the decrypted secrets cache. Call this when secrets have been rotated
 * and you need to force a fresh decrypt on the next getSecret()/getAllSecrets() call.
 */
function clearCache() {
  _cache = null;
  _pending = null;
}

module.exports = { KEYS, getSecret, getAllSecrets, clearCache };
`;
}
