import { generateRuntimeModule } from "./runtime";

describe("generateRuntimeModule", () => {
  const sampleCiphertext =
    "-----BEGIN AGE ENCRYPTED FILE-----\nabc123\n-----END AGE ENCRYPTED FILE-----";
  const sampleKeys = ["DATABASE_URL", "API_KEY"];

  describe("ESM format", () => {
    it("should generate valid ESM module source", () => {
      const source = generateRuntimeModule(sampleCiphertext, sampleKeys, "esm");

      expect(source).toContain("// Generated by clef bundle");
      expect(source).toContain("export const KEYS");
      expect(source).toContain("export async function getSecret");
      expect(source).toContain("export async function getAllSecrets");
      expect(source).toContain("DATABASE_URL");
      expect(source).toContain("API_KEY");
      expect(source).toContain(sampleCiphertext);
    });

    it("should use dynamic import for age-encryption", () => {
      const source = generateRuntimeModule(sampleCiphertext, sampleKeys, "esm");
      expect(source).toContain('import("age-encryption")');
    });

    it("should include deduplication logic", () => {
      const source = generateRuntimeModule(sampleCiphertext, sampleKeys, "esm");
      expect(source).toContain("_pending");
      expect(source).toContain("_cache");
    });

    it("should freeze KEYS array", () => {
      const source = generateRuntimeModule(sampleCiphertext, sampleKeys, "esm");
      expect(source).toContain("Object.freeze");
    });
  });

  describe("CJS format", () => {
    it("should generate valid CJS module source", () => {
      const source = generateRuntimeModule(sampleCiphertext, sampleKeys, "cjs");

      expect(source).toContain("// Generated by clef bundle");
      expect(source).toContain('"use strict"');
      expect(source).toContain("module.exports");
      expect(source).toContain("getSecret");
      expect(source).toContain("getAllSecrets");
      expect(source).toContain("KEYS");
      expect(source).not.toContain("export const");
      expect(source).not.toContain("export async");
    });

    it("should use dynamic import for age-encryption", () => {
      const source = generateRuntimeModule(sampleCiphertext, sampleKeys, "cjs");
      expect(source).toContain('import("age-encryption")');
    });
  });

  describe("edge cases", () => {
    it("should handle empty keys array", () => {
      const source = generateRuntimeModule(sampleCiphertext, [], "esm");
      expect(source).toContain("[]");
    });

    it("should escape backticks in ciphertext", () => {
      const withBackticks = "cipher`text";
      const source = generateRuntimeModule(withBackticks, ["KEY"], "esm");
      expect(source).toContain("cipher\\`text");
    });

    it("should escape backslashes in ciphertext", () => {
      const withBackslash = "cipher\\text";
      const source = generateRuntimeModule(withBackslash, ["KEY"], "esm");
      // The backslash should be double-escaped
      expect(source).toContain("cipher\\\\text");
    });

    it("should include error message for missing key", () => {
      const source = generateRuntimeModule(sampleCiphertext, sampleKeys, "esm");
      expect(source).toContain("not found");
    });
  });
});
